name: Convert Figma Tokens to CSS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install style-dictionary@latest
          npm install @tokens-studio/sd-transforms@latest
          npm install web-streams-polyfill@latest

      - name: Generate CSS from tokens
        run: npx style-dictionary build

      - name: Upload generated CSS (optional)
        uses: actions/upload-artifact@v3
        with:
          name: design-tokens-css
          path: dist/tokens.css  # Ensure this path matches where your generated CSS is located
