name: Convert Figma Tokens to CSS

on:
  workflow_dispatch

jobs:
  download-tokens:  # New job for downloading Figma tokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Figma token file
        uses: actions/download-artifact@v3
        with:
          name: design-tokens  # Match the upload artifact name
          path: tokens/

  build:
    runs-on: ubuntu-latest
    needs: download-tokens  # This job depends on download-tokens job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install style-dictionary

      - name: Generate CSS from tokens
        run: npx style-dictionary build

      - name: Upload generated CSS (optional)
        uses: actions/upload-artifact@v3
        with:
          name: design-tokens-css
          path: tokens/*.css
